// frontend/src/lib/components/search/SearchFilters.svelte
<script lang="ts">
	import { Collapsible } from 'bits-ui';
	import type { SearchFilterState } from '#lib/search/filters.svelte.ts';
	import type {
		CardType,
		FacetResponse,
		LegalityFormat,
		ManaColor,
		Rarity
	} from '#lib/search/types.ts';
	import OrnamentalDivider from '#lib/components/layout/OrnamentalDivider.svelte';

	interface Props {
		filters: SearchFilterState;
		facets?: FacetResponse | null;
		class?: string;
	}

	let { filters, facets = null, class: className = '' }: Props = $props();

	let colorsOpen = $state(true);
	let rarityOpen = $state(true);
	let typesOpen = $state(false);
	let legalityOpen = $state(false);

	const MANA_COLORS: { id: ManaColor; label: string; msClass: string }[] = [
		{ id: 'W', label: 'White', msClass: 'ms-w' },
		{ id: 'U', label: 'Blue', msClass: 'ms-u' },
		{ id: 'B', label: 'Black', msClass: 'ms-b' },
		{ id: 'R', label: 'Red', msClass: 'ms-r' },
		{ id: 'G', label: 'Green', msClass: 'ms-g' },
		{ id: 'C', label: 'Colorless', msClass: 'ms-c' }
	];

	const RARITIES: { id: Rarity; label: string; color: string }[] = [
		{ id: 'common', label: 'Common', color: 'var(--color-rarity-common)' },
		{ id: 'uncommon', label: 'Uncommon', color: 'var(--color-rarity-uncommon)' },
		{ id: 'rare', label: 'Rare', color: 'var(--color-rarity-rare)' },
		{ id: 'mythic', label: 'Mythic', color: 'var(--color-rarity-mythic)' }
	];

	const CARD_TYPES: { id: CardType; label: string }[] = [
		{ id: 'Creature', label: 'Creature' },
		{ id: 'Instant', label: 'Instant' },
		{ id: 'Sorcery', label: 'Sorcery' },
		{ id: 'Enchantment', label: 'Enchantment' },
		{ id: 'Artifact', label: 'Artifact' },
		{ id: 'Planeswalker', label: 'Planeswalker' },
		{ id: 'Land', label: 'Land' },
		{ id: 'Battle', label: 'Battle' },
		{ id: 'Kindred', label: 'Kindred' }
	];

	const LEGALITY_FORMATS: { id: LegalityFormat; label: string }[] = [
		{ id: 'standard', label: 'Standard' },
		{ id: 'pioneer', label: 'Pioneer' },
		{ id: 'modern', label: 'Modern' },
		{ id: 'legacy', label: 'Legacy' },
		{ id: 'vintage', label: 'Vintage' },
		{ id: 'commander', label: 'Commander' },
		{ id: 'pauper', label: 'Pauper' },
		{ id: 'brawl', label: 'Brawl' }
	];
</script>

<aside class="flex w-full flex-col gap-4 md:w-[240px] md:shrink-0 {className}">
	<!-- Colors section -->
	<Collapsible.Root bind:open={colorsOpen}>
		<Collapsible.Trigger
			class="flex w-full cursor-pointer items-center justify-between border-none bg-transparent py-2 font-display text-sm font-semibold text-text-secondary transition-colors hover:text-text-primary"
		>
			<span>Colors</span>
			<span
				class="inline-block transition-transform duration-200"
				style:transform={colorsOpen ? 'rotate(180deg)' : 'rotate(0deg)'}
			>
				&#9660;
			</span>
		</Collapsible.Trigger>
		<Collapsible.Content>
			<div class="flex flex-wrap gap-2 pt-2">
				{#each MANA_COLORS as color}
					<button
						onclick={() => filters.toggleColor(color.id)}
						class="flex h-9 w-9 items-center justify-center rounded-full transition-all duration-150"
						style="
							border: 2px solid {filters.selectedColors.has(color.id)
							? 'var(--color-gold-bright)'
							: 'transparent'};
							box-shadow: {filters.selectedColors.has(color.id) ? '0 0 8px var(--color-gold-dim)' : 'none'};
							opacity: {filters.selectedColors.has(color.id) ? '1' : '0.55'};
							background: none;
						"
						title={color.label}
						aria-label={color.label}
						aria-pressed={filters.selectedColors.has(color.id)}
					>
						<i
							class="ms ms-cost ms-shadow {color.msClass}"
							style="font-size: 1.6rem;"
							aria-hidden="true"
						></i>
					</button>
				{/each}
			</div>
		</Collapsible.Content>
	</Collapsible.Root>

	<OrnamentalDivider />

	<!-- Rarity section -->
	<Collapsible.Root bind:open={rarityOpen}>
		<Collapsible.Trigger
			class="flex w-full cursor-pointer items-center justify-between border-none bg-transparent py-2 font-display text-sm font-semibold text-text-secondary transition-colors hover:text-text-primary"
		>
			<span>Rarity</span>
			<span
				class="inline-block transition-transform duration-200"
				style:transform={rarityOpen ? 'rotate(180deg)' : 'rotate(0deg)'}
			>
				&#9660;
			</span>
		</Collapsible.Trigger>
		<Collapsible.Content>
			<div class="flex flex-col gap-1.5 pt-2">
				{#each RARITIES as rarity}
					<button
						onclick={() => filters.toggleRarity(rarity.id)}
						class="flex w-full items-center gap-2.5 rounded px-2 py-1.5 font-body text-sm transition-all duration-150
							{filters.selectedRarities.has(rarity.id)
							? 'text-text-primary'
							: 'text-text-secondary hover:text-text-primary'}"
						style="
							background-color: {filters.selectedRarities.has(rarity.id) ? 'var(--color-mist)' : 'transparent'};
							border: none;
							cursor: pointer;
						"
						aria-pressed={filters.selectedRarities.has(rarity.id)}
					>
						<i
							class="ms ms-rarity shrink-0"
							style="font-size: 1rem; color: {rarity.color};"
							aria-hidden="true"
						></i>
						<span class="flex-1 text-left">{rarity.label}</span>
						{#if facets?.rarity[rarity.id] != null}
							<span class="font-mono text-[10px] text-text-muted">
								{facets.rarity[rarity.id].toLocaleString()}
							</span>
						{/if}
					</button>
				{/each}
			</div>
		</Collapsible.Content>
	</Collapsible.Root>

	<OrnamentalDivider />

	<!-- Card Type section -->
	<Collapsible.Root bind:open={typesOpen}>
		<Collapsible.Trigger
			class="flex w-full cursor-pointer items-center justify-between border-none bg-transparent py-2 font-display text-sm font-semibold text-text-secondary transition-colors hover:text-text-primary"
		>
			<span>Card Type</span>
			<span
				class="inline-block transition-transform duration-200"
				style:transform={typesOpen ? 'rotate(180deg)' : 'rotate(0deg)'}
			>
				&#9660;
			</span>
		</Collapsible.Trigger>
		<Collapsible.Content>
			<div class="flex flex-wrap gap-1.5 pt-2">
				{#each CARD_TYPES as type}
					<button
						onclick={() => filters.toggleType(type.id)}
						class="rounded px-2.5 py-1 font-body text-xs transition-all duration-150"
						style="
							background-color: {filters.selectedTypes.has(type.id) ? 'var(--color-mist)' : 'transparent'};
							border: 1px solid {filters.selectedTypes.has(type.id)
							? 'var(--color-gold)'
							: 'var(--color-border)'};
							color: {filters.selectedTypes.has(type.id)
							? 'var(--color-gold-bright)'
							: 'var(--color-text-secondary)'};
							cursor: pointer;
						"
						aria-pressed={filters.selectedTypes.has(type.id)}
					>
						{type.label}
					</button>
				{/each}
			</div>
		</Collapsible.Content>
	</Collapsible.Root>

	<OrnamentalDivider />

	<!-- Legality section -->
	<Collapsible.Root bind:open={legalityOpen}>
		<Collapsible.Trigger
			class="flex w-full cursor-pointer items-center justify-between border-none bg-transparent py-2 font-display text-sm font-semibold text-text-secondary transition-colors hover:text-text-primary"
		>
			<span>Legality</span>
			<span
				class="inline-block transition-transform duration-200"
				style:transform={legalityOpen ? 'rotate(180deg)' : 'rotate(0deg)'}
			>
				&#9660;
			</span>
		</Collapsible.Trigger>
		<Collapsible.Content>
			<div class="flex flex-wrap gap-1.5 pt-2">
				{#each LEGALITY_FORMATS as format}
					<button
						onclick={() => filters.toggleLegality(format.id)}
						class="rounded px-2.5 py-1 font-body text-xs transition-all duration-150"
						style="
							background-color: {filters.selectedLegalities.has(format.id) ? 'var(--color-mist)' : 'transparent'};
							border: 1px solid {filters.selectedLegalities.has(format.id)
							? 'var(--color-gold)'
							: 'var(--color-border)'};
							color: {filters.selectedLegalities.has(format.id)
							? 'var(--color-gold-bright)'
							: 'var(--color-text-secondary)'};
							cursor: pointer;
						"
						aria-pressed={filters.selectedLegalities.has(format.id)}
					>
						{format.label}
					</button>
				{/each}
			</div>
		</Collapsible.Content>
	</Collapsible.Root>

	<!-- Clear filters -->
	{#if filters.hasFilters}
		<OrnamentalDivider />
		<button
			onclick={() => filters.clear()}
			class="cursor-pointer rounded border bg-transparent px-3 py-1.5 font-display text-xs font-semibold text-gold-bright transition-all duration-150 hover:bg-mist"
			style="border-color: var(--color-border);"
		>
			Clear Filters
		</button>
	{/if}
</aside>

// frontend/src/components/forms/SearchFilters.tsx
import { useState } from 'react'
import { ChevronDown, X, Filter } from 'lucide-react'
import type { CardSearchParams } from '@/lib/types'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { cn } from '@/lib/utils'

const COLORS = ['W', 'U', 'B', 'R', 'G', 'C']
const COLOR_LABELS: Record<string, string> = {
  W: 'White',
  U: 'Blue',
  B: 'Black',
  R: 'Red',
  G: 'Green',
  C: 'Colorless'
}
const COLOR_STYLES: Record<string, { bg: string; border: string; text: string; activeBg: string }> = {
  W: { bg: 'bg-mana-white/10', border: 'border-mana-white/30', text: 'text-mana-white', activeBg: 'bg-mana-white/20' },
  U: { bg: 'bg-mana-blue/10', border: 'border-mana-blue/30', text: 'text-mana-blue', activeBg: 'bg-mana-blue/20' },
  B: { bg: 'bg-secondary', border: 'border-muted-foreground/30', text: 'text-muted-foreground', activeBg: 'bg-secondary' },
  R: { bg: 'bg-mana-red/10', border: 'border-mana-red/30', text: 'text-mana-red', activeBg: 'bg-mana-red/20' },
  G: { bg: 'bg-mana-green/10', border: 'border-mana-green/30', text: 'text-mana-green', activeBg: 'bg-mana-green/20' },
  C: { bg: 'bg-secondary', border: 'border-muted-foreground/30', text: 'text-muted-foreground', activeBg: 'bg-secondary' },
}

const RARITIES = ['common', 'uncommon', 'rare', 'mythic']
const RARITY_STYLES: Record<string, { color: string }> = {
  common: { color: 'text-rarity-common' },
  uncommon: { color: 'text-rarity-uncommon' },
  rare: { color: 'text-rarity-rare' },
  mythic: { color: 'text-rarity-mythic' },
}

const TYPES = ['Creature', 'Instant', 'Sorcery', 'Artifact', 'Enchantment', 'Planeswalker', 'Land']

interface SearchFiltersProps {
  value: CardSearchParams
  onChange: (value: CardSearchParams) => void
}

export function SearchFilters({ value, onChange }: SearchFiltersProps) {
  const [open, setOpen] = useState(true)

  const toggleArray = (key: keyof CardSearchParams, item: string) => {
    const currentArray = (value[key] as string[]) || []
    const arr = new Set(currentArray)

    if (arr.has(item)) {
      arr.delete(item)
    } else {
      arr.add(item)
    }

    onChange({
      ...value,
      [key]: Array.from(arr),
      page: 1
    })
  }

  const clearAll = () => {
    onChange({
      q: value.q || '',
      page: 1,
      per_page: value.per_page || 24
    })
  }

  const activeCount =
    (value.colors?.length || 0) +
    (value.rarity?.length || 0) +
    (value.types?.length || 0)

  return (
    <Card className="overflow-hidden">
      <Button
        variant="ghost"
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between p-4 text-left hover:bg-card transition-colors"
      >
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center">
            <Filter className="h-4 w-4 text-primary" />
          </div>
          <span className="font-medium text-foreground">
            Advanced Filters
          </span>
          {activeCount > 0 && (
            <span className="text-xs bg-primary/15 text-primary px-2.5 py-1 rounded-full border border-primary/20">
              {activeCount} active
            </span>
          )}
        </div>
        <ChevronDown className={cn("h-4 w-4 text-muted-foreground transition-transform", open && 'rotate-180')} />
      </Button>

      {open && (
        <div className="p-4 pt-0 space-y-6 border-t border-border">
          {/* Colors */}
          <div>
            <p className="text-sm font-medium text-muted-foreground mb-3">Colors</p>
            <div className="flex flex-wrap gap-2">
              {COLORS.map((color) => {
                const isActive = value.colors?.includes(color)
                const styles = COLOR_STYLES[color]
                return (
                  <Button
                    key={color}
                    variant="outline"
                    size="sm"
                    onClick={() => toggleArray('colors', color)}
                    className={cn(
                      'h-9 px-3',
                      isActive
                        ? `${styles.activeBg} ${styles.border} ${styles.text}`
                        : `${styles.bg} ${styles.border} ${styles.text} opacity-60 hover:opacity-100`
                    )}
                  >
                    {COLOR_LABELS[color]}
                  </Button>
                )
              })}
            </div>
          </div>

          {/* Rarity */}
          <div>
            <p className="text-sm font-medium text-muted-foreground mb-3">Rarity</p>
            <div className="flex flex-wrap gap-2">
              {RARITIES.map((rarity) => {
                const isActive = value.rarity?.includes(rarity)
                const styles = RARITY_STYLES[rarity]
                return (
                  <Button
                    key={rarity}
                    variant="outline"
                    size="sm"
                    onClick={() => toggleArray('rarity', rarity)}
                    className={cn(
                      'h-9 px-3 capitalize',
                      isActive
                        ? `bg-secondary ${styles.color} border-current`
                        : 'opacity-60 hover:opacity-100'
                    )}
                  >
                    {rarity}
                  </Button>
                )
              })}
            </div>
          </div>

          {/* Card Types */}
          <div>
            <p className="text-sm font-medium text-muted-foreground mb-3">Card Types</p>
            <div className="flex flex-wrap gap-2">
              {TYPES.map((type) => {
                const isActive = value.types?.includes(type)
                return (
                  <Button
                    key={type}
                    variant="outline"
                    size="sm"
                    onClick={() => toggleArray('types', type)}
                    className={cn(
                      'h-9 px-3',
                      isActive
                        ? 'bg-primary/10 text-primary border-primary/30'
                        : 'opacity-60 hover:opacity-100'
                    )}
                  >
                    {type}
                  </Button>
                )
              })}
            </div>
          </div>

          {/* Clear Button */}
          {activeCount > 0 && (
            <div className="flex justify-end">
              <Button
                variant="ghost"
                size="sm"
                onClick={clearAll}
                className="text-muted-foreground hover:text-foreground"
              >
                <X className="h-4 w-4 mr-2" />
                Clear all filters
              </Button>
            </div>
          )}
        </div>
      )}
    </Card>
  )
}
